# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-23 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellermodel',
            name='product_list',
            field=models.TextField(default='p'),
            preserve_default=False,
        ),
    ]
