# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-23 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(default=b'', max_length=200)),
                ('image', models.ImageField(upload_to=b'products/')),
            ],
        ),
    ]
