# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-23 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=b'upload/products_images/'),
        ),
    ]
