# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-22 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=2)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('category', models.CharField(max_length=10)),
                ('seller_id', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
