# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-23 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201022_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
