# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-23 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201023_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='seller_id',
        ),
    ]
